-- 記事の版1つにつき提案は1つまで（TASKS F-1）。
--
-- **同じ版を二度提案しない。** 提案は LINE 通知を伴うため、二重に作ると
-- 同じ記事の確認依頼が2通届く。SPEC 8.3 は「同一提案を連続通知しない」と
-- 定めており、通知の側で数えるより**作れないようにするほうが確実**。
--
-- 状態を問わない全体の一意にしている。見送られた版を作り直さないためで、
-- 修正依頼を受けたときは E-10 が `version_no` を増やした**新しい版**を作る
-- （`article_versions` は上書きしない）。つまり再提案は常に別の版になる。
--
-- 部分インデックス（`WHERE status IN (...)`）にしないのは、Prisma が
-- `WHERE` 付きインデックスを表現できず、`schema.prisma` との差分検査に
-- 引っかかるため。全体の一意なら Prisma がそのまま持てる。
CREATE UNIQUE INDEX "approvals_article_version_id_key" ON "approvals"("article_version_id");
